---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: nginx
  namespace: nginx
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - nginx
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: high
  name: nginx
  namespace: nginx
spec:
  type: Git
  pathname: https://github.com/fazifs/sandbox.git
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: kustomize
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: nginx
  name: nginx
  namespace: nginx
spec:
  allow:
    - apiVersion: policy.open-cluster-management.io/v1
      kinds:
        - "*"
    - apiVersion: apps.open-cluster-management.io/v1
      kinds:
        - PlacementRule
  channel: nginx
  placement:
    placementRef:
      kind: PlacementRule
      name: nginx-placement
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: nginx
  name: nginx-placement
  namespace: nginx
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: local-cluster
        operator: In
        values:
          - "true"
